# Generated by Django 4.2.1 on 2023-05-28 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_alter_booking_no_of_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookingDate',
            new_name='booking_date',
        ),
    ]
